"""empty message

Revision ID: 0383fe67795d
Revises: 14d89c00321b
Create Date: 2024-06-04 15:10:06.121650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0383fe67795d'
down_revision = '14d89c00321b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_custid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customer', ['payment_custid'], ['cust_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_custid')

    # ### end Alembic commands ###
