"""empty message

Revision ID: 14d89c00321b
Revises: a5fff122693d
Create Date: 2024-05-31 17:42:38.671675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14d89c00321b'
down_revision = 'a5fff122693d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('prod_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_quantity', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
