"""empty message

Revision ID: 415da35d091a
Revises: 9245187eb881
Create Date: 2024-05-30 13:44:26.720622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415da35d091a'
down_revision = '9245187eb881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_ref')

    # ### end Alembic commands ###
