"""empty message

Revision ID: 7f9bcc2bf8d0
Revises: 
Create Date: 2024-05-22 19:39:08.227355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9bcc2bf8d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_pwd', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=False),
    sa.Column('last_loggedin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('product',
    sa.Column('prod_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_description', sa.String(length=225), nullable=False),
    sa.Column('prod_title', sa.String(length=100), nullable=False),
    sa.Column('prod_price', sa.String(length=100), nullable=False),
    sa.Column('prod_availability', sa.Enum('Available', 'Out of Stock'), server_default='Available', nullable=True),
    sa.Column('prod_catid', sa.Integer(), nullable=True),
    sa.Column('prod_date', sa.DateTime(), nullable=True),
    sa.Column('prod_image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['prod_catid'], ['category.cat_id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('state_lgaid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_lgaid'], ['lga.lga_id'], ),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('customer',
    sa.Column('cust_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_fname', sa.String(length=100), nullable=False),
    sa.Column('cust_lname', sa.String(length=100), nullable=False),
    sa.Column('cust_email', sa.String(length=120), nullable=False),
    sa.Column('cust_address', sa.String(length=120), nullable=True),
    sa.Column('cust_password', sa.String(length=255), nullable=True),
    sa.Column('cust_phone', sa.String(length=120), nullable=True),
    sa.Column('cust_pix', sa.String(length=120), nullable=True),
    sa.Column('cust_lgaid', sa.Integer(), nullable=True),
    sa.Column('cust_stateid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_lgaid'], ['lga.lga_id'], ),
    sa.ForeignKeyConstraint(['cust_stateid'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_custid', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_custid'], ['customer.cust_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_orderid', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('transaction_details', sa.String(length=100), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['payment_orderid'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('prod_order',
    sa.Column('prod_orderid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['product.prod_id'], ),
    sa.PrimaryKeyConstraint('prod_orderid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prod_order')
    op.drop_table('payment')
    op.drop_table('order')
    op.drop_table('customer')
    op.drop_table('state')
    op.drop_table('product')
    op.drop_table('lga')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
