"""empty message

Revision ID: 9110445f2c95
Revises: 04e9ec8356dc
Create Date: 2024-06-04 17:52:10.190782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9110445f2c95'
down_revision = '04e9ec8356dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cust_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
