"""empty message

Revision ID: f0945777d531
Revises: 7f9bcc2bf8d0
Create Date: 2024-05-26 10:51:10.619021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0945777d531'
down_revision = '7f9bcc2bf8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_quantity', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('prod_quantity')

    # ### end Alembic commands ###
