"""empty message

Revision ID: f17c3d0ea4b7
Revises: 415da35d091a
Create Date: 2024-05-30 14:27:54.740133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17c3d0ea4b7'
down_revision = '415da35d091a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('pending', 'paid', 'failed'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('pending', 'paid', 'failed'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
